"""adds a hashtag table relatade to post table

Revision ID: 5ba6da7572c7
Revises: 60c283a02c7f
Create Date: 2019-09-21 17:35:34.817600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba6da7572c7'
down_revision = '60c283a02c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('blogs', 'hash_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('hash_tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('hashtags')
    # ### end Alembic commands ###
