"""changes column name in the blog table

Revision ID: 60c283a02c7f
Revises: 97f1da430529
Create Date: 2019-09-21 17:24:06.294111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c283a02c7f'
down_revision = '97f1da430529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('hash_tags', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'has_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('has_tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'hash_tags')
    # ### end Alembic commands ###
