"""Add a stranger comment table

Revision ID: 72621f9cfb5e
Revises: 964414ed26ea
Create Date: 2019-09-24 04:40:06.017565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72621f9cfb5e'
down_revision = '964414ed26ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strange_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strange_comment')
    # ### end Alembic commands ###
